#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

[options]
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = "myspacevim#before"

[[layers]]
  name = "default"

[[layers]]
  name = "edit"

[[layers]]
  name = "tools"

[[layers]]
  name = "core#statusline"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "lang#ruby"
  repl_command = "pry"

[[layers]]
  name = "lang#coffeescript"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "tmux"

[[layers]]
  name = "tags"

[[layers]]
  name = "fzf"

[[layers]]
  name = "checkers"

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"
