#!/usr/bin/env zsh

backup=$HOME/OneDrive/Backup
gpgdir=$backup/workstation/gpg
source ~/.zsh/utils.sh

highlight "Checking if OneDrive is setup correctly.."
[[ -d $gpgdir ]] || error "Please, make sure that $gpgdir is available."

highlight "Setting up GnuPG"
gpg --import $gpgdir/secret.key
rm ~/.gnupg/trustdb.gpg
gpg --import-ownertrust <$gpgdir/trustdb.txt

highlight "Checking if I can access git@github.com with newly set GPG key"
ssh -T git@github.com 2>&1 | grep $(whoami) || error "SSH from GPG did not work!"

highlight "Checking if I can source secret files.."
source_secret ~/.dotfiles/secret/zshenv.asc
source ~/.zsh/aliases.zsh

highlight "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:nikhgupta/dotcastle.git"

highlight "Updating system"
sudo apt-get update
sudo apt-get upgrade -y

highlight "Installing dependencies"
sudo apt install -y curl wget make \
    libssl-dev automake autoconf libreadline-dev \
    libncurses5-dev zlib1g-dev build-essential libbz2-dev \
    libsqlite3-dev libncursesw5-dev libffi-dev liblzma-dev

highlight "Installing utilities"
sudo apt install -y curl wget make zsh vim tmux aria2 \
    rclone ripgrep fd-find jq inotify-tools ncdu

highlight "Installing asdf"
git clone https://github.com/asdf-vm/asdf.git ~/.asdf
cd ~/.asdf
git checkout "$(git describe --abbrev=0 --tags)"
asdfin() { asdf install $@ && asdf global $@; }

highlight "Setting up global gitconfig"
git config --global core.editor $EDITOR
git config --global user.name $NICK
git config --global user.email $EMAIL
git config --global github.user $NICK
git config --global github.token $GITHUB_TOKEN
git config --global github.password $GITHUB_TOKEN
git config --global github.oauth-token $GITHUB_TOKEN
git config --global user.signingkey $GPGKEY
git config --global commit.gpgsign true

highlight "Installing VIM plugins"
vim +PlugInstall +qall

highlight "Installing required components"
sudo apt install -y postgresql redis-server default-jre default-jdk

highlight "Installing node.js"
asdf plugin add nodejs
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
asdfin nodejs 14.4.0

highlight "Installing erlang/elixir"
asdf plugin add erlang
asdf plugin add elixir
sudo apt install -y m4 wx-common libwxgtk3.0-gtk3-dev
sudo apt install -y libxml2-utils xsltproc fop unixodbc unixodbc-dev
asdfin erlang 23.0.2
asdfin elixir 1.10.3-otp-23

highlight "Installing ruby"
asdf plugin add ruby
asdfin ruby 2.7.1

highlight "Installing python"
sudo apt install -y llvm xz-utils tk-dev python-openssl
asdf plugin add python
asdf install python 2.7.18
asdfin python 3.8.3

highlight "Installing Youtube-DL"
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

highlight "Installing AntiBody"
curl -sfL git.io/antibody | sudo sh -s - -b /usr/local/bin
antibody bundle <~/.zsh/plugs.txt >~/.zshplugs
