#!/usr/bin/env bash

name="ubuntu"
dir="$HOME/.dotfiles"

sudo apt-get update
sudo apt-get upgrade -y

sudo apt install git curl wget stow make build-essential wget curl llvm xz-utils
sudo apt install build-essentials fasd ntfs-3g

# install ruby, python, nodejs
sudo apt install ruby nodejs npm python3 python3-pip

# miscelleneous

# dotfiles
# git clone https://github.com/nikhgupta/dotcastle $dir
# stow -t $HOME -v -d $dir $name --ignore=.gitconfig
# rm -f ~/.gitconfig
# cp $dir/$name/.gitconfig ~/.gitconfig
# ln -sf $dir/$name/.gitignore ~/.gitignore

# gitconfig
git config --global core.editor $EDITOR
git config --global user.name $NICK
git config --global user.email $EMAIL
git config --global github.user $NICK
git config --global github.token $GITHUB_TOKEN
git config --global github.password $GITHUB_TOKEN
git config --global github.oauth-token $GITHUB_TOKEN
git config --global sendmail.smtpuser $EMAIL

vim +PlugInstall +qall
