#!/usr/bin/env sh
#
# git-cron - Script para enviar automaticamente mudanças ao Github
# LEMBRE-SE DE CONFIGURAR CORRETAMENTE SEU GIT SEM SENHA!!!
#
# Desenvolvido por Lucas Saliés Brum <lucas@archlinux.com.br>
#
# Sugestão de crontab:
# */15 * * * * sh -c "~/.local/bin/git-cron" > /dev/null 2>&1
#
# Criado em: 20/12/2017 19:27:31
# Última Atualização: 03/05/2018 17:38:14

dir="${HOME}/github"
repos=('majestic' 'sistematico.github.io' 'oc-cli' 'cabron-bot' 'pollen' 'agressive')

atualiza() {
	if [ -d $1 ]; then
		if [ ! -f $1/.noup ]; then
			cd $1
			status=$(git add . -n)
			if [ ! -z "$status" ]; then
			c=$(echo $(git add . -n | tr '\r\n' ' '))
			m="Autocommit por Git-Cron: alterações: $c"
			git add .
			git commit -m "$m"
			git push
				if [ "$DESKTOP_SESSION" == "i3" ]; then
					DISPLAY=:0 notify-send "Git Cron" "Repo <b>$(basename $1)</b> atualizado."
				fi
			fi
		fi
	fi
}

if [ ! $1 ]; then
	for r in "${repos[@]}";	do
		caminho="${dir}/${r}"
		atualiza "$caminho"
	done
else
	caminho="$@"
	atualiza "$caminho"
fi

