#!/usr/bin/env ruby
#
# ---------------------------------------------------------------------
#
#   Summary: Read readme file for the given gem in Browser
#   Author:  Nikhil Gupta
#   Usage:   gem-readme <gem-name>
#
# ---------------------------------------------------------------------
#

require 'optparse'
ARGV.options do |opts|
  opts.on("-h", "--help") { puts %x(list-commands #{$0}); exit(0) }
  opts.parse!
end

begin
  spec = Gem::Specification.find_by_name(ARGV.first)

  readme_bin = File.join(File.dirname(__FILE__), "readme")
  system "#{readme_bin} #{spec.gem_dir}"
rescue Gem::MissingSpecError
  puts "\e[4;31mError\e[0m: No such gem found: #{ARGV.first}"
  exit
end
