#! /bin/sh

# Kill all running applications before starting
killall -9 sxhkd compton dunst redshift syndaemon

sxhkd &

bspc monitor -d web term code music files mail chat settings automation 9
# bspc monitor -d I II III IV V VI VII VIII IX X

bspc desktop ^1 -l monocle
bspc desktop ^2 -l tiled
bspc desktop ^3 -l monocle
bspc desktop ^4 -l tiled
bspc desktop ^5 -l monocle
bspc desktop ^6 -l monocle
bspc desktop ^7 -l tiled

bspc config borderless_monocle    true
bspc config click_to_focus        true
# bspc config focus_follows_pointer true
bspc config gapless_monocle       true
# bspc config paddingless_monocle   true
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
# bspc config pointer_modifier      mod4
bspc config presel_feedback_color "#aaaaaa"
bspc config normal_border_color   "#85888f"
bspc config focused_border_color  "#5FAD56"

bspc config split_ratio           0.52
bspc config window_gap            20
# bspc config border_radius         5
bspc config border_width          0

bspc config super                 mod4

# remove all rules first
bspc rule -r *:*
# float
bspc rule -a Alacritty:fzfmenu              state=tiled center=on focus=on
bspc rule -a xmessage                       state=floating center=on focus=on
bspc rule -a Dialog                         state=floating center=on
bspc rule -a htop                           state=floating center=on
bspc rule -a display                        state=floating center=on
bspc rule -a display.im6                    state=floating center=on
bspc rule -a xev                            state=floating center=on
bspc rule -a trayer                         state=floating sticky=on
bspc rule -a feh                            state=floating manage=off
bspc rule -a Nvidia-settings                state=floating focus=on
bspc rule -a Pavucontrol                    state=floating focus=on center=on
bspc rule -a Pulseaudio-equalizer-gtk       state=floating focus=on
bspc rule -a Pulseffects                    state=floating focus=on
bspc rule -a alsamixer                      state=floating focus=on
# bspc rule -a Kupfer.py focus=on

# desktop 1 - web
bspc rule -a Firefox                        desktop=^1 follow=on
bspc rule -a Google-chrome                  desktop=^1 follow=on
bspc rule -a Chromium                       desktop=^1 follow=on
bspc rule -a qutebrowser                    desktop=^1 follow=on

# desktop 2 - terminals/landing/homepage
bspc rule -a urxvt                          desktop=^2 follow=on focus=on
bspc rule -a xterm                          desktop=^2 follow=on focus=on
bspc rule -a xfce4-terminal                 desktop=^2 follow=on focus=on
bspc rule -a xfontsel                       desktop=^2 follow=on focus=on
bspc rule -a easystroke                     desktop=^2 follow=on focus=on
bspc rule -a Termite                        desktop=^2 follow=on focus=on
bspc rule -a Gnome-terminal                 desktop=^2 follow=on focus=on
bspc rule -a Alacritty                      desktop=^2 follow=on focus=on

# desktop 3 - code
bspc rule -a Atom                           desktop=^3 follow=on
bspc rule -a Subl3                          desktop=^3 follow=on
bspc rule -a Code                           desktop=^3 follow=on
bspc rule -a Genymotion                     desktop=^3
bspc rule -a Notepadqq                      desktop=^3 follow=on
bspc rule -a Mousepad                       desktop=^3 follow=on
bspc rule -a Gedit                          desktop=^3 state=floating

# desktop 4 - music/videos
bspc rule -a mpv                            desktop=^4 follow=on state=floating center=on focus=on
bspc rule -a vlc                            desktop=^4 follow=on state=floating center=on focus=on
bspc rule -a Spotify                        desktop=^4
bspc rule -a Spacefm                        desktop=^4 follow=on
bspc rule -a Alacritty:ncmpcpp              desktop=^4 follow=on
bspc rule -a mplayer2                       desktop=^4 state=floating
bspc rule -a Alacritty:lyricist             desktop=^4 follow=on

# desktop 5 - files, torrents, etc.
bspc rule -a Alacritty:ranger               desktop=^5 follow=on focus=on
bspc rule -a Org.gnome.Nautilus             desktop=^5 follow=on focus=on
bspc rule -a Thunar                         desktop=^5 follow=on focus=on
bspc rule -a Deluge                         desktop=^5 follow=on
bspc rule -a Transmission-gtk               desktop=^5 follow=on
bspc rule -a qBittorrent                    desktop=^5 follow=on
bspc rule -a Zathura                        desktop=^5 follow=on state=tiled
bspc rule -a Gimp                           desktop=^5 state=floating follow=on
bspc rule -a Darktable                      desktop=^5 state=floating follow=on
bspc rule -a Caja                           desktop=^5 follow=on
bspc rule -a File-roller                    desktop=^5 state=floating center=on
bspc rule -a nitrogen                       desktop=^5 state=floating focus=on
bspc rule -a dde-file-manager               desktop=^5 follow=on focus=on

# desktop 7 - chats
bspc rule -a TelegramDesktop                desktop=^7 follow=on

# desktop 8 - tools, utils
bspc rule -a GParted                        desktop=^8 follow=on focus=on
bspc rule -a Gnome-system-monitor           desktop=^8 state=floating center=on follow=on focus=on
bspc rule -a deepin-system-monitor           desktop=^8 state=floating center=on follow=on focus=on

# desktop 9 - miscelleneous
bspc rule -a Steam                          desktop=^9 follow=on

# scripts
#feh --bg-fill "/home/gamehelp16/Pictures/unsplashwall.jpg"
#feh --bg-fill ~/Pictures/zF1V6EE.jpg
#feh --randomize --bg-fill /media/JukeBox/Wallpapers
feh --bg-fill $XDG_WALLPAPER_DIR/_default.jpg
#gnome-wallpaper-changer &
compton -b
xrdb -merge ~/.Xdefaults
#redshift &
#/home/gamehelp16/allfloat.sh &
xsetroot -cursor_name left_ptr
# syndaemon -dkK -i 0.8 &
light -S 45 # https://github.com/haikarainen/light

#panel &
~/.config/polybar/launch.sh &
