#!/usr/bin/env ruby

require_relative "./controller"

MONITOR_SETUPS = {
  mac: {
    "macbook": "5C2E8D42-8D34-1841-9F5B-DC325C6DB2E9",
  },
  work: {
    "macbook": "5C2E8D42-8D34-1841-9F5B-DC325C6DB2E9",
    "lenovo": "5F07D30E-33D6-66B5-B6EA-343FF18B7CB3",
  },
}

SPACES = [
  term: { icon: " ", displays: %w[macbook] },
  web: { icon: " ", displays: %w[lenovo macbook] },
  code: { icon: " ", displays: %w[macbook] },
  media: { icon: "", displays: %w[lenovo macbook] },
  files: { icon: " ", displays: %w[macbook] },
  mail: { icon: "\uFAEF", displays: %w[lenovo macbook] },
  social: { icon: " ", displays: %w[macbook] },
  office: { icon: " ", displays: %w[lenovo macbook] },
  settings: { icon: " ", displays: %w[macbook] },
  tools: { icon: " ", displays: %w[lenovo macbook] },
]

yabaictl = Yabai::Controller.new(spaces_count: 10, monitors: MONITOR_SETUPS)

command = ARGV.shift
yabaictl.send(command, *ARGV) if yabaictl.respond_to?(command)
