#!/usr/bin/env bash

source ~/.zsh/utils.sh
if is_installed neofetch; then
  if is_archlinux; then
    /usr/bin/neofetch --ascii_distro arch --backend ascii --disable distro kernel $@
  elif is_ubuntu || is_wsl_ubuntu; then
    /usr/bin/neofetch --ascii_distro ubuntu --backend ascii --disable distro kernel $@
  else
    /usr/bin/neofetch --backend ascii --disable distro kernel $@
  fi
fi
