#!/usr/bin/env bash

# Simple bash script to check download speed

url="https://ia800703.us.archive.org/34/items/1mbFile/1mb.mp4"  #   1120 KB

usage() { echo "Usage: $0 [-q|v]" 1>&2; exit 1; }

a=" "
while getopts ":qv" o; do
    case "${o}" in
        v) a="${a} -v";;
        q) a="${a} -q";;
        *) usage ;;
    esac
done
shift $((OPTIND-1))

t=$(date +"%s")
wget "${url}" $a -t 3 -O ->/dev/null

echo "------------------------------------------------------------------------"
echo -ne "Download speed is: "
echo -ne $(expr 8 \* 100 / $(($(date +"%s")-$t)))
echo "KB/s"
echo "------------------------------------------------------------------------"
