#!/usr/bin/env zsh
#
# ---------------------------------------------------------------------
#
#   Summary:     Generates local SSL certs and add it to the keychain.
#   Author:      Nikhil Gupta
#   Description: Generates local SSL certificates for the client
#                machine with optional wildcard support. It, further,
#                adds generated SSL certificates to the OSX Keychain.
#   Usage:       gen-ssl [-w|--wildcard] [-h|--help]
#
# ---------------------------------------------------------------------
#

o_wildcard=(); o_help=();
zparseopts -D -E -K -- w=o_wildcard -wildcard=o_wildcard h=o_help -help=o_help

if [[ $# == 0 || $? != 0 || -n "$o_help" ]]; then
  list-commands $0
  exit 1
fi

[[ -n "${o_wildcard}" ]] && name=wildcard      || name=single
[[ -n "${o_wildcard}" ]] && common_name="*.$1" || common_name="$1"

if [ -z $1 ]; then
  echo "Usage: gen_wildcard_ssl <domain.com> [-w|--wildcard]"
  exit
elif [ -d /private/etc/apache2/ssl/$1/$name.cert ]; then
  echo "Path: /private/etc/apache2/ssl/$1/$name.cert already exists."
  exit
fi

mkdir /tmp/sslcert
pushd /tmp/sslcert

(umask 077 && touch $name.key $name.cert $name.info $name.pem)

openssl genrsa 2048 > $name.key
openssl req -new -x509 -nodes -sha1 -days 3650 -key $name.key \
  -subj "/C=IN/ST=Rajasthan/L=Jaipur/O=Nikhil Gupta/OU=IT/CN=${common_name}" > $name.cert
openssl x509 -noout -fingerprint -text < $name.cert > $name.info

cat $name.cert $name.key > $name.pem
chmod 400 $name.key $name.pem

sudo mkdir /private/etc/apache2/ssl/$1 2>/dev/null
sudo mv $name.key $name.pem $name.cert $name.info /private/etc/apache2/ssl/$1

popd
rm -rf /tmp/sslcert

echo "\n====="
echo "Certificate generation completed."
echo "Created at: /private/etc/apache2/ssl/$1/$name.cert"

sudo security add-trusted-cert -d -r trustRoot -k \
  "/Library/Keychains/System.keychain" /private/etc/apache2/ssl/$1/$name.cert

echo "Certificate marked as trusted in OSX Keychain."
