#!/usr/bin/env bash
#
# ---------------------------------------------------------------------
#
#   Summary:     Empty trash and run other housekeeping in MacOS
#   Author:      Nikhil Gupta
#   Description: Empty the Trash on all mounted volumes and the main
#                HDD. Also, clear Apple’s System Logs to improve shell
#                startup speed. Finally, clear download history from
#                quarantine. https://mths.be/bum
#   Usage:       housekeep
#   TODOs:       - for other linux systems
#
# ---------------------------------------------------------------------
#

[[ "$1" == "-h" ]] || [[ "$1" == "--help" ]] && list-commands $0 && exit 1
source $(dirname $0)/helpers/utils.sh

if is_macosx; then
  echo "Emptying trash.."
  sudo rm -rfv ~/.Trash
  echo "Emptying trash on all external volumes.."
  sudo rm -rfv /Volumes/*/.Trashes
  echo "cleaning up Mac asl files.."
  sudo rm -rfv /private/var/log/asl/*.asl
  echo "cleaning up Quarantine Events.."
  sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'
fi

