#!/usr/bin/env bash
#
# ---------------------------------------------------------------------
#
#   Summary: Script that produces a cow telling you about your fortune.
#   Author:  Nikhil Gupta
#   Usage:   tunecow [-r|--random]
#
# ---------------------------------------------------------------------
#

[[ "$1" == "-h" ]] || [[ "$1" == "--help" ]] && list-commands $0 && exit 1
which fortune &>/dev/null || brew install fortune
which cowsay  &>/dev/null || brew install cowsay

if [ "$1" == "--random" -o "$1" == "-r" ]; then
  IFS=' '
  figures=(`cowsay -l | tail -n +2 | tr '\n' ' '`)
  num_figures=${#figures[*]}
  figure=${figures[$((RANDOM%num_figures))]}
  fortune -s | cowsay -f $figure
else
  fortune -s | cowsay
fi
