#!/bin/bash

# xwinwrap -ov -fs -- /usr/lib/xscreensaver/glslideshow -delay 0 -window-id WID -zoom 100

if [ $1 ]; then
	caminho="$1"
else
	caminho="${HOME}/img/wallpapers/"
fi

while true; do
	xwinwrap -b -fs -sp -fs -nf -ov -- feh --randomize --bg-fill $caminho
	sleep 10
done
