" settings for Solarized:
" let g:solarized_termcolors=256
" let g:solarized_termtrans=1
" let g:solarized_contrast="high"
" let g:solarized_visibility="high"

" Use a nice font on the specific OS {{{
if g:is_mac
  set guifont=Monaco\ For\ Powerline:h12
elseif g:is_windows
    set guifont=Bitstream\ Vera\ Sans\ Mono:h11
elseif g:is_linux
    set guifont=Monospace\ 11
endif
" }}}

" Open MacVim in fullscreen mode {{{
if g:is_macvim
  set fuoptions=maxvert,maxhorz
  au GUIEnter * set fullscreen
endif
" }}}

" Adjust the GUI accordingly {{{
  set guioptions-=T   " Remove the toolbar
  set guioptions-=m   " Remove the menu
  set guioptions+=c   " Use console dialogs

  " remove scrollbars
  set guioptions-=r
  set guioptions-=R
  set guioptions-=l
  set guioptions-=L
" }}}

" Disable cursor blinking and set it to be a block
" set guicursor+=a:blinkon0
" cursor does not blink for nvc modes
let &guicursor = substitute(&guicursor, 'n-v-c:', '&blinkon0-', '')
set guicursor+=a:block-Cursor

" Custom tabs label
set guitablabel=%t\ %m

" Maximize gvim window
set lines=999 columns=999

" Reload Gvim configuration automatically {{{
  if has("autocmd")
    augroup AutoReloadGVimRC
      au!
      au BufWritePost $MYGVIMRC so $MYGVIMRC
      " au BufWritePost $MYGVIMRC call Pl#Load()
    augroup END
  endif
" }}}

 " to enable:
  " hex highlighting
  " QFix
  " change cursor type when in insert mode
  " when starting using, say: 'mvim .',
  "   MacVim should have NerdTree in a left pane
  " delete a whole fold


