#!/usr/bin/env sh
#
#   Configuration inside `~/.zshenv` is source by both interactive and
#   not interactive shells (typically, GUI programs), and hence, MacVim
#   is able to pick configuration defined in this file. This is
#   essential, since some plugins in MacVim requires some secret
#   environment variables to be setup, as well as, rbenv support is
#   required for working with rails in VIM.
#
#   `~/.zshenv` should not contain configuration that is meant for
#   interactive shells, e.g. prompts, aliases, etc., unless o'course,
#   you want that to be so.
#

# zmodload zsh/zprof

# => all the dotfiles code resides here, so this will be used often
export DOTCASTLE=$HOME/Code/dotcastle
source $DOTCASTLE/terminal/utils.sh
setenv DOTCASTLE $DOTCASTLE

# => setup editor for ourself
setenv EDITOR    vim
setenv VISUAL    vim
setenv GUIEDITOR vimr
# setenv BROWSER   "open -a 'Google Chrome'"
# browser(){ eval "$BROWSER '$1'"; }; alias browse=browser

# => other OSX dependent environment variables and mods
if is_macosx; then
  setenv BREW_PREFIX /usr/local
  export HOMEBREW_CASK_OPTS="--appdir=/Applications"
else
  export BREW_PREFIX=$HOME/.linuxbrew
fi

setenv ZSH "$HOME/.oh-my-zsh" # required by OhMyZSH!

# => ensure that homebrew is in our path.
path_prepend "${BREW_PREFIX}/bin"
path_prepend "${BREW_PREFIX}/sbin"

# load rbenv and pyenv, if available
setenv RBENV_ROOT $BREW_PREFIX/var/rbenv
is_installed rbenv && init_cache rbenv "rbenv init --no-rehash - zsh"
setenv PYENV_ROOT $BREW_PREFIX/var/pyenv
is_installed pyenv && init_cache pyenv "pyenv init --no-rehash - zsh"
is_installed pyenv-virtualenv-init && init_cache pyenv-virtualenv-init "pyenv virtualenv-init -"

# Python environment
# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
# allow access to install python packages globally via gpip
gpip(){ PIP_REQUIRE_VIRTUALENV="" pip "$@"; }
gpip3(){ PIP_REQUIRE_VIRTUALENV="" pip3 "$@"; }

# GO Language
setenv GOPATH $HOME/Code/workspace/go
path_append "${GOPATH}/bin"
path_append "${BREW_PREFIX}/opt/go/libexec/bin"

# => load local configuration, if available
path_prepend $DOTCASTLE/bin
ssh-add $HOME/.ssh/`whoami` &>/dev/null || echo "SSH identity could not be added!"
[[ -s ~/.zshenv.local ]] && source ~/.zshenv.local
export GPG_TTY=$(tty)
