#! /bin/sh

# Kill all running applications before starting
killall -9 sxhkd picom dunst mpd polybar

source ~/.zshenv
sxhkd &

bspc monitor -d web term code music files mail chat settings automation 9
# bspc monitor -d I II III IV V VI VII VIII IX X

bspc desktop ^1 -l monocle
bspc desktop ^2 -l tiled
bspc desktop ^3 -l monocle
bspc desktop ^4 -l tiled
bspc desktop ^5 -l monocle
bspc desktop ^6 -l monocle
bspc desktop ^7 -l tiled

bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true
# bspc config click_to_focus        true
# bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
# bspc config pointer_modifier      mod4
bspc config presel_feedback_color "#aaaaaa"
bspc config normal_border_color "#393b47"
bspc config focused_border_color "#5af78e"

bspc config split_ratio 0.52
bspc config window_gap 10
bspc config border_width 2

# bspc config super                 mod4

# remove all rules first
bspc rule -r *:*
# float
bspc rule -a $TERMINAL_CLASS:fzfmenu state=tiled center=on focus=on
bspc rule -a xmessage state=floating center=on focus=on
bspc rule -a Dialog state=floating center=on
bspc rule -a htop state=floating center=on
bspc rule -a display state=floating center=on
bspc rule -a display.im6 state=floating center=on
bspc rule -a xev state=floating center=on
bspc rule -a trayer state=floating sticky=on
bspc rule -a feh state=floating manage=off
bspc rule -a Nvidia-settings state=floating focus=on
bspc rule -a Pavucontrol state=floating focus=on center=on
bspc rule -a blueman-manager state=floating focus=on center=on follow=on
bspc rule -a Pulseaudio-equalizer-gtk state=floating focus=on
bspc rule -a Pulseffects state=floating focus=on
bspc rule -a alsamixer state=floating focus=on
bspc rule -a io.elementary.shortcut-overlay state=floating focus=on
bspc rule -a io.elementary.calculator state=floating focus=on
bspc rule -a io.elementary.calendar state=floating focus=on
bspc rule -a io.elementary.screenshot-tool state=floating focus=on
bspc rule -a ScratchTerm state=floating sticky=on layer=above locked=on focus=on hidden=on rectangle=1924x322+-2+-2
# bspc rule -a Kupfer.py focus=on

# desktop 1 - web
bspc rule -a Firefox desktop=^1 follow=on
bspc rule -a Google-chrome desktop=^1 follow=on
bspc rule -a Chromium desktop=^1 follow=on
bspc rule -a qutebrowser desktop=^1 follow=on

# desktop 2 - terminals/landing/homepage
bspc rule -a $TERMINAL_CLASS desktop=^2 follow=on focus=on
bspc rule -a urxvt desktop=^2 follow=on focus=on
bspc rule -a xterm desktop=^2 follow=on focus=on
bspc rule -a xfce4-terminal desktop=^2 follow=on focus=on
bspc rule -a xfontsel desktop=^2 follow=on focus=on
bspc rule -a easystroke desktop=^2 follow=on focus=on
bspc rule -a Termite desktop=^2 follow=on focus=on
bspc rule -a Gnome-terminal desktop=^2 follow=on focus=on
bspc rule -a Alacritty desktop=^2 follow=on focus=on
bspc rule -a kitty desktop=^2 follow=on focus=on
bspc rule -a io.elementary.terminal desktop=^2 follow=on focus=on

# desktop 3 - code
bspc rule -a Atom desktop=^3 follow=on
bspc rule -a Subl3 desktop=^3 follow=on
bspc rule -a Code desktop=^3 follow=on
bspc rule -a Emacs desktop=^3 follow=on
bspc rule -a Genymotion desktop=^3
bspc rule -a Notepadqq desktop=^3 follow=on
bspc rule -a Mousepad desktop=^3 follow=on
bspc rule -a Gedit desktop=^3 state=floating
bspc rule -a io.elementary.code desktop=^3 state=floating

# desktop 4 - music/videos
bspc rule -a mpv desktop=^4 follow=on state=floating center=on focus=on
bspc rule -a vlc desktop=^4 follow=on state=floating center=on focus=on
bspc rule -a Spotify desktop=^4
bspc rule -a Spacefm desktop=^4 follow=on
bspc rule -a $TERMINAL_CLASS:ncmpcpp desktop=^4 follow=on
bspc rule -a mplayer2 desktop=^4 state=floating
bspc rule -a $TERMINAL_CLASS:lyricist desktop=^4 follow=on
bspc rule -a io.elementary.music desktop=^4 follow=on
bspc rule -a io.elementary.videos desktop=^4 follow=on
bspc rule -a io.elementary.photos desktop=^4 follow=on
bspc rule -a io.elementary.camera desktop=^4 follow=on

# desktop 5 - files, torrents, etc.
bspc rule -a $TERMINAL_CLASS:ranger desktop=^5 follow=on focus=on
bspc rule -a Org.gnome.Nautilus desktop=^5 follow=on focus=on
bspc rule -a Thunar desktop=^5 follow=on focus=on
bspc rule -a Deluge desktop=^5 follow=on
bspc rule -a Transmission-gtk desktop=^5 follow=on
bspc rule -a qBittorrent desktop=^5 follow=on
bspc rule -a Zathura desktop=^5 follow=on state=tiled
bspc rule -a Gimp desktop=^5 state=floating follow=on
bspc rule -a Darktable desktop=^5 state=floating follow=on
bspc rule -a Caja desktop=^5 follow=on
bspc rule -a File-roller desktop=^5 state=floating center=on
bspc rule -a nitrogen desktop=^5 state=floating focus=on
bspc rule -a dde-file-manager desktop=^5 follow=on focus=on
bspc rule -a Io.elementary.files desktop=^5 follow=on focus=on

# desktop 6 - mail and messages
bspc rule -a Mailspring desktop=^6 follow=on focus=on

# desktop 7 - chats
bspc rule -a weechat desktop=^7 follow=on
bspc rule -a Slack desktop=^7 follow=on
bspc rule -a Skype desktop=^7 follow=on
bspc rule -a TelegramDesktop desktop=^7 follow=on

# desktop 8 - tools, utils
bspc rule -a GParted desktop=^8 follow=on focus=on
bspc rule -a Gnome-system-monitor desktop=^8 state=floating center=on follow=on focus=on
bspc rule -a deepin-system-monitor desktop=^8 state=floating center=on follow=on focus=on
bspc rule -a io.elementary.switchboard desktop=^8 state=floating center=on follow=on focus=on

# desktop 9 - miscelleneous
bspc rule -a Steam desktop=^9 follow=on

# === Startup Environment =========
# Scripts to set a familiar environment when we login
_wall=$(cat ~/.wall)
feh --bg-fill "${_wall:-~/Pictures/Wallpapers/default.png}"
numlockx off # turn off num lock on login
light -S 45 # set a specific screen backlight
pactl set-source-mute @DEFAULT_SOURCE@ 1 # mute microphone on login
pgrep mpd && mpc stop # turn off music in the rare case that it is running

# === Startup Items ===============

# start Polkit for authenticating user session and use sudo in GUI
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# lets start with our polybar first of all..
~/.config/polybar/launch.sh &

# useful daemons and processes
mpd
dunst &
picom -b
xrdb -merge ~/.Xdefaults
xsetroot -cursor_name left_ptr

# System Tray processes
pamac-tray &
nm-applet &
blueman-applet &

# start libinput gestures for touchpad
libinput-gestures-setup start

# start hidden scratch terminal window
$TERMINAL --class ScratchTerm &

# start redshift
is_installed redshift-gtk && redshift-gtk &
! is_installed redshift-gtk && is_installed redshift && redshift &

# Auto-lock after suspend. https://wiki.archlinux.org/index.php/Power_management#xss-lock
xss-lock -- ~/.bin/screenlock.sh &

# Auto-lock after some time but not when cursor is parked at bottom right.
xautolock -locker ~/.bin/screenlock.sh -time 5 -detectsleep -corners '00+-' &
